# Data ====
inflow_sql <- paste0("
SELECT *
FROM 
(SELECT 
  EXTRACT(DATE FROM CHARTTIME_COLLAPSED) AS CHART_DATE,
  EXTRACT(HOUR FROM CHARTTIME_COLLAPSED) AS CHART_HOUR,
  CURR_CAREUNIT AS CURR_UNIT, 
  COUNT(DISTINCT CGID) AS STAFF
FROM `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS_COLLAPSED_NEW`
GROUP BY CHART_DATE, CHART_HOUR, CURR_UNIT) AS L
LEFT JOIN 
(SELECT 
  ICUSTAY_ID,
  CURR_CAREUNIT AS CURR_UNIT,
  IFNULL(ANY_VALUE(PREV_CAREUNIT), ", "'OUT'" , ") AS PREV_CAREUNIT,
  EXTRACT(DATE FROM ANY_VALUE(INTIME_TRANS_COLLAPSED)) AS CHART_DATE,
  EXTRACT(HOUR FROM ANY_VALUE(INTIME_TRANS_COLLAPSED)) AS CHART_HOUR,
  #EXTRACT(DATE FROM ANY_VALUE(OUTTIME_TRANS_COLLAPSED)) AS out_date,
  #EXTRACT(HOUR FROM ANY_VALUE(OUTTIME_TRANS_COLLAPSED)) AS out_hour,
  #ANY_VALUE(LOS_TRANS) AS los,
  ANY_VALUE(LOS_TRANS) / COUNT(DISTINCT CGID) AS los_pro
FROM `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS_COLLAPSED_NEW`
GROUP BY ICUSTAY_ID, CURR_UNIT) AS R

USING (CHART_DATE, CHART_HOUR, CURR_UNIT)
ORDER BY CHART_DATE, CHART_HOUR
 ")

inflow <- dbGetQuery(con, inflow_sql)

# Data ====
outflow_sql <- paste0("
SELECT 
  ICUSTAY_ID,
  CURR_CAREUNIT, 
  EXTRACT(DATE FROM ANY_VALUE(OUTTIME_TRANS_COLLAPSED)) AS OUT_DATE,
  EXTRACT(HOUR FROM ANY_VALUE(OUTTIME_TRANS_COLLAPSED)) AS OUT_HOUR
FROM `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS_COLLAPSED_NEW`
GROUP BY ICUSTAY_ID, CURR_CAREUNIT
ORDER BY OUT_DATE, OUT_HOUR
")
                
outflow <- dbGetQuery(con, outflow_sql) %>% 
  select(-c(ICUSTAY_ID)) %>% 
  group_by(CURR_CAREUNIT, OUT_DATE, OUT_HOUR) %>% 
  summarise(OUTFLOW = n())


df <- inflow  %>% 
  left_join(y = outflow, by =  c("CURR_UNIT" = "CURR_CAREUNIT", "CHART_DATE" = "OUT_DATE", "CHART_HOUR" = "OUT_HOUR")) %>%
  glimpse()





