-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
SELECT
  *, 
  DATETIME_ADD(CHARTTIME, INTERVAL shifts.SHIFT_1 DAY) AS CHARTTIME_SHIFT_1,
  DATETIME_ADD(CHARTTIME, INTERVAL shifts.SHIFT_2 DAY) AS CHARTTIME_SHIFT_2,
  DATETIME_ADD(CHARTTIME, INTERVAL shifts.SHIFT_3 DAY) AS CHARTTIME_SHIFT_3,
  DATETIME_ADD(CHARTTIME, INTERVAL shifts.SHIFT_4 DAY) AS CHARTTIME_SHIFT_4,
  DATETIME_ADD(CHARTTIME, INTERVAL shifts.SHIFT_5 DAY) AS CHARTTIME_SHIFT_5
  FROM (
    SELECT
    *
  FROM
    `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS`) AS charts
LEFT JOIN (
  SELECT
    *
  FROM
    `MIMIC3_V1_4.TIME_SHIFT`) AS shifts
USING
  (ICUSTAY_ID)
  


