-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
SELECT
  *, 
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED), INTERVAL charts.SHIFT_1 DAY) AS INTIME_COLLAPSED_SHIFT_1,
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED), INTERVAL charts.SHIFT_2 DAY) AS INTIME_COLLAPSED_SHIFT_2,
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED), INTERVAL charts.SHIFT_3 DAY) AS INTIME_COLLAPSED_SHIFT_3,
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED), INTERVAL charts.SHIFT_4 DAY) AS INTIME_COLLAPSED_SHIFT_4,
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED), INTERVAL charts.SHIFT_5 DAY) AS INTIME_COLLAPSED_SHIFT_5
  FROM (
    SELECT
    *
  FROM
    `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS`) AS charts
LEFT JOIN (
  SELECT
    ICUSTAY_ID, INTIME_COLLAPSED, OUTIME_COLLAPSED
  FROM
    `MIMIC3_V1_4.ICUSTAYS_COLLAPSED`) AS icustays
USING
  (ICUSTAY_ID)

  


