-- !preview conn=DBI::dbConnect(RSQLite::SQLite())
SELECT
  *,
  DATETIME_ADD(DATETIME(icustays.INTIME_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED,
  DATETIME_ADD(DATETIME(icustays.INTIME_SHIFT_1_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED_SHIFT_1,
  DATETIME_ADD(DATETIME(icustays.INTIME_SHIFT_2_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED_SHIFT_2,
  DATETIME_ADD(DATETIME(icustays.INTIME_SHIFT_3_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED_SHIFT_3,
  DATETIME_ADD(DATETIME(icustays.INTIME_SHIFT_4_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED_SHIFT_4,
  DATETIME_ADD(DATETIME(icustays.INTIME_SHIFT_5_COLLAPSED),
    INTERVAL TIMESTAMP_DIFF(TIMESTAMP(charts.CHARTTIME), icustays.INTIME, MINUTE) MINUTE) AS CHARTTIME_COLLAPSED_SHIFT_5
FROM (
  SELECT
    *
  FROM
    `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS`) AS charts
LEFT JOIN (
  SELECT
    INTIME,
    OUTTIME, 
    ICUSTAY_ID,
    INTIME_COLLAPSED,
    INTIME_SHIFT_1_COLLAPSED,
    INTIME_SHIFT_2_COLLAPSED,
    INTIME_SHIFT_3_COLLAPSED,
    INTIME_SHIFT_4_COLLAPSED,
    INTIME_SHIFT_5_COLLAPSED,
    LOS
  FROM
    `MIMIC3_V1_4.ICUSTAYS_COLLAPSED`) AS icustays
USING
  (ICUSTAY_ID)


