SELECT
  *
FROM (
  SELECT
  *
  FROM
    MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS_COLLAPSED) AS CHARTS
LEFT JOIN (
  SELECT
    ICUSTAY_ID,
    INTIME_TRANS_COLLAPSED,
    OUTTIME_TRANS_COLLAPSED,
    INTIME_TRANS_SHIFT_1_COLLAPSED,
    INTIME_TRANS_SHIFT_2_COLLAPSED,
    INTIME_TRANS_SHIFT_3_COLLAPSED,
    INTIME_TRANS_SHIFT_4_COLLAPSED,
    INTIME_TRANS_SHIFT_5_COLLAPSED,
    OUTTIME_TRANS_SHIFT_1_COLLAPSED,
    OUTTIME_TRANS_SHIFT_2_COLLAPSED,
    OUTTIME_TRANS_SHIFT_3_COLLAPSED,
    OUTTIME_TRANS_SHIFT_4_COLLAPSED,
    OUTTIME_TRANS_SHIFT_5_COLLAPSED,
    DATETIME(INTIME_TRANS) AS INTIME_TRANS_DT,
    DATETIME(OUTTIME_TRANS) AS OUTTIME_TRANS_DT
FROM
    MIMIC3_V1_4.ICUSTAYS_TRANS_COLLAPSED ) AS TRANS_NEW
USING
  (ICUSTAY_ID)
WHERE
  TRANS_NEW.INTIME_TRANS_DT < CHARTS.CHARTTIME
  AND CHARTS.CHARTTIME < TRANS_NEW.OUTTIME_TRANS_DT 
 
