SELECT
  *
FROM (
  SELECT
    SUBJECT_ID,
    HADM_ID,
    ICUSTAY_ID,
    ITEMID,
    CHARTTIME,
    CGID
  FROM
    MIMIC3_V1_4.CHARTEVENTS) AS charts
LEFT JOIN (
  SELECT
    SUBJECT_ID,
    INTIME,
    OUTTIME,
    PREV_CAREUNIT,
    CURR_CAREUNIT,
    LOS
  FROM
    MIMIC3_V1_4.TRANSFERS ) AS trans
USING
  (SUBJECT_ID)
WHERE
  trans.INTIME < charts.CHARTTIME
  AND charts.CHARTTIME < trans.OUTTIME