SELECT
LABEL, COUNT(LABEL) as LABEL_n
FROM (
  SELECT
  *
    FROM (
      SELECT
      CGID
      FROM
      `MIMIC3_V1_4.CHARTEVENTS_DEPTS_CATS_TS_COLLAPSED_NEW`)
  LEFT JOIN (
    SELECT
    *
      FROM
    `MIMIC3_V1_4.CAREGIVERS`) AS b
  USING
  (CGID))
GROUP BY LABEL
ORDER BY LABEL_n DESC